version: "3.1"
services:
 frontend:
    build: ./front-end
    container_name: frontend_container
    volumes:
      - frontend:/front-end
    ports:
      - "3000:3000"
    depends_on:
      - api
 api:
    build: ./api
    container_name: api_container
    volumes:
      - api:/api
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/business_db
    depends_on:
      - db

 db_data:
  build: ./db_data
  environment:
        DB_CONNECTION_STRING: "postgres://postgres:docker@db:5432/business_db"
  depends_on:
        - frontend

 db:
    image: postgres:latest
    container_name: db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: business_db
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  frontend:
  api:
  db: